### ISSUE TITLE
Configuration missing

### ISSUE THREAD

**Issue by atrus05** [frli4797/homebridge-sector#1]
Hi there @frli4797 ,

I have installed the plugin in Homebridge, but you have not yet added the configuration to the readme, so I can't get this up and running. This is the one that they use for the verisure plugin, I assume it is something very similar, but if one do not figure out the exact wording for the platform key, then the homebridge service goes into a continous reboot during startup. Can you enlighten me what to use?
```
"platforms": [
  {
    "platform" : "verisure",
    "name" : "Verisure",
    "email": "your@email.com",
    "password": "yourT0p5ecre7Passw0rd",
    "alarmCode": "0000",
    "doorCode": "000000",
    "pollInterval": 60
  }
]
```

**Comment by atrus05** [comment]
If you want me to write up a readme for you, and push it to you, just let me know. But I need that value in that case :)

**Comment by frli4797** [comment]
I never thought that anyone would dare use it. :D

I can push a readme and a config file example, hopefully by tomorrow. This
plugin is very much in an alpha state at best, but whom ever want to
contribute is very welcome.

I’ll also outline any plans for the development in the readme.


tis 20 nov. 2018 kl. 19:45 skrev Daniel Eriksson <notifications@github.com>:

**Comment by atrus05** [comment]
I am brave, and eager to try it out. :)
I am interested to know if the different sensors that are connected to the alarm system can be acted upon in my Homekit solution.
When door opens, do this. When noone is home anymore, arm the alarm. And so on.

I understand that it might never happen, but I am keeping my hopes up that this is the start which will lead us to a perfect solution :)

PS: Säg till om du vill bolla lite ideer utanför Github via valfritt protokoll!
