### ISSUE TITLE
Additional comments

### ISSUE THREAD

**Issue by atrus05** [frli4797/homebridge-sector#3]
Great work so far. I recommend adding an additional comment to the config. I have yet to figure out how to find my "site ID" which you mention. I can't find it in the manual, on the panel itself (have not removed it from the wall to check the backside though as I am afraid to trip some kind of alarm), nor by logging into minasidor.sectoralarm.se. How did you find yours? Is it the 8 digits in the URL after I login to Mina Sidor?

**Comment by frli4797** [comment]
Correct. Site it can be found in the url like you mention. I used to be able to find it in the app as well, but that isn't possible anymore.
